<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="case.test_userinfo.TestUserinfo" tests="3" time="3.021">
	<testcase classname="case.test_userinfo.TestUserinfo" name="test_get_empty" time="1.007"/>
	<testcase classname="case.test_userinfo.TestUserinfo" name="test_get_success" time="1.007"/>
	<testcase classname="case.test_userinfo.TestUserinfo" name="test_set_success" time="1.007"/>
	<system-out>
<![CDATA[{'errno': 102, 'data': [], 'errmsg': 'not exist user'}
1437895284
{'errno': 0, 'data': [{'modtime': '2015-07-26 15:21:24', 'status': 1, 'name': '', 'mobile': '', 'addtime': None, 'gender': 1, 'mail': '', 'uid': 1437895284}], 'errmsg': ''}
1437895285
{'errno': 0, 'errmsg': ''}
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
